import { ProductionProvider } from "@/context/ProductionContext";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "SEP490",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry> 
          <ProductionProvider>
            {children}
            <ToastContainer />
          </ProductionProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}