import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { ProductionProvider } from "@/context/ProductionContext";

export const metadata: Metadata = {
  title: "SEP490",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProductionProvider>
        <body>{children}</body>
      </ProductionProvider>
    </html>
  );
}
